// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: value_status.proto

package api

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type ValueState int32

const (
	// ValueState_NONEXISTENT is assigned to value that was deleted or has never
	// existed.
	ValueState_NONEXISTENT ValueState = 0
	// ValueState_MISSING is assigned to NB value that was configured but refresh
	// found it to be missing.
	ValueState_MISSING ValueState = 1
	// ValueState_UNIMPLEMENTED marks value received from NB that cannot
	// be configured because there is no registered descriptor associated
	// with it.
	ValueState_UNIMPLEMENTED ValueState = 2
	// ValueState_REMOVED is assigned to NB value after it was removed or when
	// it is being re-created. The state is only temporary: for re-create, the
	// value transits to whatever state the following Create operation produces,
	// and delete values are removed from the graph (go to the NONEXISTENT state)
	// immediately after the notification about the state change is sent.
	ValueState_REMOVED ValueState = 3
	// ValueState_CONFIGURED marks value defined by NB and successfully configured.
	ValueState_CONFIGURED ValueState = 4
	// ValueState_OBTAINED marks value not managed by NB, instead created
	// automatically or externally in SB. The KVScheduler learns about the value
	// either using Retrieve() or through a SB notification.
	ValueState_OBTAINED ValueState = 5
	// ValueState_DISCOVERED marks NB value that was found (=retrieved) by refresh
	// but not actually configured by the agent in this run.
	ValueState_DISCOVERED ValueState = 6
	// ValueState_PENDING represents (NB) value that cannot be configured yet
	// due to missing dependencies.
	ValueState_PENDING ValueState = 7
	// ValueState_INVALID represents (NB) value that will not be configured
	// because it has a logically invalid content as declared by the Validate
	// method of the associated descriptor.
	// The corresponding error and the list of affected fields are stored
	// in the <InvalidValueDetails> structure available via <details> for invalid
	// value.
	ValueState_INVALID ValueState = 8
	// ValueState_FAILED marks (NB) value for which the last executed operation
	// returned an error.
	// The error and the type of the operation which caused the error are stored
	// in the <FailedValueDetails> structure available via <details> for failed
	// value.
	ValueState_FAILED ValueState = 9
	// ValueState_RETRYING marks unsucessfully applied (NB) value, for which,
	// however, one or more attempts to fix the error by repeating the last
	// operation are planned, and only if all the retries fail, the value will
	// then transit to the FAILED state.
	ValueState_RETRYING ValueState = 10
	// ValueState_WAITING marks value which is waiting for another value within
	// the same transaction to be processed first (KVScheduler internal state).
	ValueState_WAITING ValueState = 11
	// ValueState_INPROGRESS marks value that is being Created/Updated/Deleted
	// asynchronously from another go routine (KVScheduler internal state).
	ValueState_INPROGRESS ValueState = 12
)

var ValueState_name = map[int32]string{
	0:  "NONEXISTENT",
	1:  "MISSING",
	2:  "UNIMPLEMENTED",
	3:  "REMOVED",
	4:  "CONFIGURED",
	5:  "OBTAINED",
	6:  "DISCOVERED",
	7:  "PENDING",
	8:  "INVALID",
	9:  "FAILED",
	10: "RETRYING",
	11: "WAITING",
	12: "INPROGRESS",
}

var ValueState_value = map[string]int32{
	"NONEXISTENT":   0,
	"MISSING":       1,
	"UNIMPLEMENTED": 2,
	"REMOVED":       3,
	"CONFIGURED":    4,
	"OBTAINED":      5,
	"DISCOVERED":    6,
	"PENDING":       7,
	"INVALID":       8,
	"FAILED":        9,
	"RETRYING":      10,
	"WAITING":       11,
	"INPROGRESS":    12,
}

func (x ValueState) String() string {
	return proto.EnumName(ValueState_name, int32(x))
}

func (ValueState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5e25aca3c33dcc40, []int{0}
}

type TxnOperation int32

const (
	TxnOperation_UNDEFINED TxnOperation = 0
	TxnOperation_VALIDATE  TxnOperation = 1
	TxnOperation_CREATE    TxnOperation = 2
	TxnOperation_UPDATE    TxnOperation = 3
	TxnOperation_DELETE    TxnOperation = 4
)

var TxnOperation_name = map[int32]string{
	0: "UNDEFINED",
	1: "VALIDATE",
	2: "CREATE",
	3: "UPDATE",
	4: "DELETE",
}

var TxnOperation_value = map[string]int32{
	"UNDEFINED": 0,
	"VALIDATE":  1,
	"CREATE":    2,
	"UPDATE":    3,
	"DELETE":    4,
}

func (x TxnOperation) String() string {
	return proto.EnumName(TxnOperation_name, int32(x))
}

func (TxnOperation) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5e25aca3c33dcc40, []int{1}
}

type ValueStatus struct {
	Key           string       `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	State         ValueState   `protobuf:"varint,2,opt,name=state,proto3,enum=api.ValueState" json:"state,omitempty"`
	Error         string       `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	LastOperation TxnOperation `protobuf:"varint,4,opt,name=last_operation,json=lastOperation,proto3,enum=api.TxnOperation" json:"last_operation,omitempty"`
	// - for invalid value, details is a list of invalid fields
	// - for pending value, details is a list of missing dependencies (labels)
	Details              []string `protobuf:"bytes,5,rep,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValueStatus) Reset()         { *m = ValueStatus{} }
func (m *ValueStatus) String() string { return proto.CompactTextString(m) }
func (*ValueStatus) ProtoMessage()    {}
func (*ValueStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e25aca3c33dcc40, []int{0}
}
func (m *ValueStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValueStatus.Unmarshal(m, b)
}
func (m *ValueStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValueStatus.Marshal(b, m, deterministic)
}
func (m *ValueStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValueStatus.Merge(m, src)
}
func (m *ValueStatus) XXX_Size() int {
	return xxx_messageInfo_ValueStatus.Size(m)
}
func (m *ValueStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ValueStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ValueStatus proto.InternalMessageInfo

func (m *ValueStatus) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ValueStatus) GetState() ValueState {
	if m != nil {
		return m.State
	}
	return ValueState_NONEXISTENT
}

func (m *ValueStatus) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ValueStatus) GetLastOperation() TxnOperation {
	if m != nil {
		return m.LastOperation
	}
	return TxnOperation_UNDEFINED
}

func (m *ValueStatus) GetDetails() []string {
	if m != nil {
		return m.Details
	}
	return nil
}

type BaseValueStatus struct {
	Value                *ValueStatus   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	DerivedValues        []*ValueStatus `protobuf:"bytes,2,rep,name=derived_values,json=derivedValues,proto3" json:"derived_values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BaseValueStatus) Reset()         { *m = BaseValueStatus{} }
func (m *BaseValueStatus) String() string { return proto.CompactTextString(m) }
func (*BaseValueStatus) ProtoMessage()    {}
func (*BaseValueStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e25aca3c33dcc40, []int{1}
}
func (m *BaseValueStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseValueStatus.Unmarshal(m, b)
}
func (m *BaseValueStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseValueStatus.Marshal(b, m, deterministic)
}
func (m *BaseValueStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseValueStatus.Merge(m, src)
}
func (m *BaseValueStatus) XXX_Size() int {
	return xxx_messageInfo_BaseValueStatus.Size(m)
}
func (m *BaseValueStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseValueStatus.DiscardUnknown(m)
}

var xxx_messageInfo_BaseValueStatus proto.InternalMessageInfo

func (m *BaseValueStatus) GetValue() *ValueStatus {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *BaseValueStatus) GetDerivedValues() []*ValueStatus {
	if m != nil {
		return m.DerivedValues
	}
	return nil
}

func init() {
	proto.RegisterEnum("api.ValueState", ValueState_name, ValueState_value)
	proto.RegisterEnum("api.TxnOperation", TxnOperation_name, TxnOperation_value)
	proto.RegisterType((*ValueStatus)(nil), "api.ValueStatus")
	proto.RegisterType((*BaseValueStatus)(nil), "api.BaseValueStatus")
}

func init() { proto.RegisterFile("value_status.proto", fileDescriptor_5e25aca3c33dcc40) }

var fileDescriptor_5e25aca3c33dcc40 = []byte{
	// 418 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xcf, 0x6e, 0xda, 0x40,
	0x10, 0xc6, 0x63, 0x8c, 0x21, 0x8c, 0xf9, 0xb3, 0x59, 0xf5, 0xe0, 0x23, 0x8a, 0xd4, 0x0a, 0xe5,
	0xc0, 0x21, 0x3d, 0xb4, 0x57, 0x87, 0x1d, 0xd0, 0x4a, 0xb0, 0x46, 0xeb, 0x85, 0xb6, 0x27, 0xe4,
	0x8a, 0x3d, 0x58, 0x45, 0xb1, 0xe5, 0x35, 0x51, 0xfb, 0x56, 0x7d, 0x8d, 0xbe, 0x55, 0x35, 0x4b,
	0x93, 0xa6, 0x52, 0x6f, 0xf3, 0xcd, 0x6f, 0xbe, 0x6f, 0x66, 0x2d, 0x03, 0x7f, 0x2a, 0x4e, 0x67,
	0x7b, 0x70, 0x6d, 0xd1, 0x9e, 0xdd, 0xbc, 0x6e, 0xaa, 0xb6, 0xe2, 0x61, 0x51, 0x97, 0xb7, 0x3f,
	0x03, 0x88, 0xf7, 0xc4, 0x72, 0x8f, 0x38, 0x83, 0xf0, 0x9b, 0xfd, 0x91, 0x04, 0xd3, 0x60, 0x36,
	0xd0, 0x54, 0xf2, 0xb7, 0x10, 0x91, 0xcd, 0x26, 0x9d, 0x69, 0x30, 0x1b, 0xdf, 0x4f, 0xe6, 0x45,
	0x5d, 0xce, 0x5f, 0x2c, 0x56, 0x5f, 0x28, 0x7f, 0x03, 0x91, 0x6d, 0x9a, 0xaa, 0x49, 0x42, 0x6f,
	0xbd, 0x08, 0xfe, 0x11, 0xc6, 0xa7, 0xc2, 0xb5, 0x87, 0xaa, 0xb6, 0x4d, 0xd1, 0x96, 0xd5, 0x63,
	0xd2, 0xf5, 0x29, 0x37, 0x3e, 0xc5, 0x7c, 0x7f, 0xcc, 0x9e, 0x81, 0x1e, 0xd1, 0xe0, 0x8b, 0xe4,
	0x09, 0xf4, 0x8f, 0xb6, 0x2d, 0xca, 0x93, 0x4b, 0xa2, 0x69, 0x38, 0x1b, 0xe8, 0x67, 0x79, 0xdb,
	0xc0, 0xe4, 0xa1, 0x70, 0xf6, 0xf5, 0xd5, 0xef, 0x20, 0xf2, 0x0f, 0xf4, 0x77, 0xc7, 0xf7, 0xec,
	0xdf, 0x1b, 0xcf, 0x4e, 0x5f, 0x30, 0xff, 0x00, 0xe3, 0xa3, 0x6d, 0xca, 0x27, 0x7b, 0x3c, 0xf8,
	0x86, 0x4b, 0x3a, 0xd3, 0xf0, 0xbf, 0x86, 0xd1, 0x9f, 0x39, 0xdf, 0x73, 0x77, 0xbf, 0x02, 0x80,
	0xbf, 0x6f, 0xe6, 0x13, 0x88, 0x55, 0xa6, 0xf0, 0xb3, 0xcc, 0x0d, 0x2a, 0xc3, 0xae, 0x78, 0x0c,
	0xfd, 0x8d, 0xcc, 0x73, 0xa9, 0x56, 0x2c, 0xe0, 0x37, 0x30, 0xda, 0x29, 0xb9, 0xd9, 0xae, 0x71,
	0x83, 0xca, 0xa0, 0x60, 0x1d, 0xe2, 0x1a, 0x37, 0xd9, 0x1e, 0x05, 0x0b, 0xf9, 0x18, 0x60, 0x91,
	0xa9, 0xa5, 0x5c, 0xed, 0x34, 0x0a, 0xd6, 0xe5, 0x43, 0xb8, 0xce, 0x1e, 0x4c, 0x2a, 0x15, 0x0a,
	0x16, 0x11, 0x15, 0x32, 0x5f, 0x64, 0x7b, 0x24, 0xda, 0x23, 0xeb, 0x16, 0x95, 0xa0, 0xe8, 0x3e,
	0x09, 0xa9, 0xf6, 0xe9, 0x5a, 0x0a, 0x76, 0xcd, 0x01, 0x7a, 0xcb, 0x54, 0xae, 0x51, 0xb0, 0x01,
	0x65, 0x68, 0x34, 0xfa, 0x0b, 0x8d, 0x01, 0x8d, 0x7d, 0x4a, 0xa5, 0x21, 0x11, 0x53, 0xa0, 0x54,
	0x5b, 0x9d, 0xad, 0x34, 0xe6, 0x39, 0x1b, 0xde, 0x65, 0x30, 0x7c, 0xfd, 0xe1, 0xf9, 0x08, 0x06,
	0x3b, 0x25, 0x70, 0xe9, 0xf7, 0x5f, 0x51, 0x92, 0x5f, 0x90, 0x1a, 0x64, 0x01, 0xed, 0x58, 0x68,
	0xa4, 0xba, 0x43, 0xf5, 0x6e, 0xeb, 0xfb, 0x21, 0xd5, 0x02, 0xd7, 0x68, 0x90, 0x75, 0xbf, 0xf6,
	0xfc, 0xff, 0xf4, 0xfe, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x55, 0xe5, 0xf7, 0xc6, 0x65, 0x02,
	0x00, 0x00,
}
